export enum labels {
  WEBSITE_TITLE = "Simulador de Investimentos",
  SIMULATE_LABEL = "Simular",
  SIMULATOR = "Simulador",
  CLEAR_FIELDS_LABEL = "Limpar campos",
  SIMULATOR_INCOME = "Rendimento",
  GROSS_INCOME = "Bruto",
  NET_INCOME = "Líquido",
  INITIAL_CONTRIBUTION = "Aporte Inicial",
  TERM = "Prazo (em meses)",
  IPCA = "IPCA (ao ano)",
  MONTHLY_CONTRIBUTION = "Aporte Mensal",
  PROFITABILITY = "Rentabilidade",
  INDEXING_TYPES = "Tipos de indexação",
  CDI = "CDI (ao ano)",
  PRE = "PRÉ",
  POST = "POS",
  FIXED = "FIXADO",
  VALUE = "Valor (R$)",
  TIME = "Tempo (meses)",
  SIMULATION_RESULT = "Resultado da Simulação",
  PROJECTION_OF_VALUES = "Projeção de Valores",
  GROSS_FINAL_VALUE = "Valor final Bruto",
  INCOME_TAX_RATE = "Alíquota do IR",
  AMOUNT_PAID_IN_IR = "Valor Pago em IR",
  NET_FINAL_VALUE = "Valor Final Líquido",
  TOTAL_AMOUNT_INVESTED = "Valor Total Investido",
  NET_GAIN = "Ganho Líquido",
}

export enum fieldNames {
  INITIAL_CONTRIBUTION = "initialContribution",
  TERM = "term",
  IPCA = "ipca",
  MONTHLY_CONTRIBUTION = "montlyContribution",
  PROFITABILITY = "profitability",
  CDI = "cdi",
}
